vich_uploader:
    db_driver: orm

    mappings:
        articles:
            uri_prefix: /images/articles
            upload_destination: '%kernel.project_dir%/public/images/articles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        consultations:
            uri_prefix: /images/consultations
            upload_destination: '%kernel.project_dir%/public/images/consultations'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        
        about:
            uri_prefix: /images/about
            upload_destination: '%kernel.project_dir%/public/images/about'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        
        approche:
            uri_prefix: /images/about
            upload_destination: '%kernel.project_dir%/public/images/about'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        activities:
            uri_prefix: /images/activities
            upload_destination: '%kernel.project_dir%/public/images/activities'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        ateliers:
            uri_prefix: /images/ateliers
            upload_destination: '%kernel.project_dir%/public/images/ateliers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        product_covers:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/products/covers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        product_ebooks:
            uri_prefix: /ebooks/products
            upload_destination: '%kernel.project_dir%/public/ebooks/products'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options:
                    property: fileName